package procuidado.model;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cuidador generated by hbm2java
 */
public class Cuidador extends Persona implements java.io.Serializable
{

	private boolean esCuidadorPorDefecto;
	private String telefono1;
	private String telefono2;
	private Set residentes = new HashSet(0);
	private Set casas = new HashSet(0);
	private String nom;
	private String cognom;
	private String tipoDeDocumento;
	private String documento;
	/**
	 * @return the nom
	 */
	public String getNom() {
		return nom;
	}

	/**
	 * @param nom the nom to set
	 */
	public void setNom(String nom) {
		this.nom = nom;
	}

	/**
	 * @return the cognom
	 */
	public String getCognom() {
		return cognom;
	}

	/**
	 * @param cognom the cognom to set
	 */
	public void setCognom(String cognom) {
		this.cognom = cognom;
	}

	/**
	 * @return the tipoDeDocumento
	 */
	public String getTipoDeDocumento() {
		return tipoDeDocumento;
	}

	/**
	 * @param tipoDeDocumento the tipoDeDocumento to set
	 */
	public void setTipoDeDocumento(String tipoDeDocumento) {
		this.tipoDeDocumento = tipoDeDocumento;
	}

	/**
	 * @return the documento
	 */
	public String getDocumento() {
		return documento;
	}

	/**
	 * @param documento the documento to set
	 */
	public void setDocumento(String documento) {
		this.documento = documento;
	}

	private Set restricciones = new HashSet(0);

	public Cuidador() {
	}

	public Cuidador(boolean esCuidadorPorDefecto, String telefono1)
	{
		this.esCuidadorPorDefecto = esCuidadorPorDefecto;
		this.telefono1 = telefono1;
	}

	public Cuidador(boolean esCuidadorPorDefecto, String telefono1, String telefono2, Set residentes, Set casas)
	{
		this.esCuidadorPorDefecto = esCuidadorPorDefecto;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.residentes = residentes;
		this.casas = casas;
	}

	public int getIdentificador()
	{
		return super.getIdentificador();
	}

	public void setIdentificador(int identificador)
	{
		super.setIdentificador(identificador);
	}

	
	public boolean isEsCuidadorPorDefecto()
	{
		return this.esCuidadorPorDefecto;
	}

	public void setEsCuidadorPorDefecto(boolean esCuidadorPorDefecto)
	{
		this.esCuidadorPorDefecto = esCuidadorPorDefecto;
	}

	public String getTelefono1()
	{
		return this.telefono1;
	}

	public void setTelefono1(String telefono1)
	{
		this.telefono1 = telefono1;
	}

	public String getTelefono2()
	{
		return this.telefono2;
	}

	public void setTelefono2(String telefono2)
	{
		this.telefono2 = telefono2;
	}

	public Set getResidentes()
	{
		return this.residentes;
	}

	public void setResidentes(Set residentes)
	{
		this.residentes = residentes;
	}

	public Set getCasas()
	{
		return this.casas;
	}

	public void setCasas(Set casas)
	{
		this.casas = casas;
	}
	public Set getRestricciones()
	{
		return this.restricciones;
	}

	public void setRestricciones(Set restricciones)
	{
		this.restricciones = restricciones;
	}

}
