package procuidado.model;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Residente generated by hbm2java
 */
public class Residente extends Persona implements java.io.Serializable
{

	private Estancia estancia;
	private Casa casa;
	private Set cuidadors = new HashSet(0);

	public Residente()
	{
	}

	public Residente(Estancia estancia, Casa casa, Set cuidadors)
	{
		this.estancia = estancia;
		this.casa = casa;
		this.cuidadors = cuidadors;
	}

	public int getIdentificador()
	{
		return super.getIdentificador();
	}

	public void setIdentificador(int identificador)
	{
		super.setIdentificador(identificador);
	}

	public Estancia getEstancia()
	{
		return this.estancia;
	}

	public void setEstancia(Estancia estancia)
	{
		this.estancia = estancia;
	}

	public Casa getCasa()
	{
		return this.casa;
	}

	public void setCasa(Casa casa)
	{
		this.casa = casa;
	}

	public Set getCuidadors()
	{
		return this.cuidadors;
	}

	public void setCuidadors(Set cuidadors)
	{
		this.cuidadors = cuidadors;
	}

}
