package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Calendario generated by hbm2java
 */
public class Calendario implements java.io.Serializable {

	private int identificador;
	private String nombre;
	private String color;
	private String descripcion;
	private Set recordatorios = new HashSet(0);

	public Calendario() {
	}

	public Calendario(int identificador) {
		this.identificador = identificador;
	}

	public Calendario(int identificador, String nombre, String color,
			String descripcion, Set recordatorios) {
		this.identificador = identificador;
		this.nombre = nombre;
		this.color = color;
		this.descripcion = descripcion;
		this.recordatorios = recordatorios;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getRecordatorios() {
		return this.recordatorios;
	}

	public void setRecordatorios(Set recordatorios) {
		this.recordatorios = recordatorios;
	}

}
