package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ConstanteVital generated by hbm2java
 */
public class ConstanteVital implements java.io.Serializable {

	private int identificador;
	private boolean estaActiva;
	private String nombre;
	private Set constanteActivas = new HashSet(0);

	public ConstanteVital() {
	}

	public ConstanteVital(int identificador, boolean estaActiva, String nombre) {
		this.identificador = identificador;
		this.estaActiva = estaActiva;
		this.nombre = nombre;
	}

	public ConstanteVital(int identificador, boolean estaActiva, String nombre,
			Set constanteActivas) {
		this.identificador = identificador;
		this.estaActiva = estaActiva;
		this.nombre = nombre;
		this.constanteActivas = constanteActivas;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public boolean isEstaActiva() {
		return this.estaActiva;
	}

	public void setEstaActiva(boolean estaActiva) {
		this.estaActiva = estaActiva;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getConstanteActivas() {
		return this.constanteActivas;
	}

	public void setConstanteActivas(Set constanteActivas) {
		this.constanteActivas = constanteActivas;
	}

}
