package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * ConstanteLeida generated by hbm2java
 */
public class ConstanteLeida implements java.io.Serializable {

	private ConstanteLeidaId id;
	private ConstanteActiva constanteActiva;

	public ConstanteLeida() {
	}

	public ConstanteLeida(ConstanteLeidaId id, ConstanteActiva constanteActiva) {
		this.id = id;
		this.constanteActiva = constanteActiva;
	}

	public ConstanteLeidaId getId() {
		return this.id;
	}

	public void setId(ConstanteLeidaId id) {
		this.id = id;
	}

	public ConstanteActiva getConstanteActiva() {
		return this.constanteActiva;
	}

	public void setConstanteActiva(ConstanteActiva constanteActiva) {
		this.constanteActiva = constanteActiva;
	}

}
