package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ConstanteActiva generated by hbm2java
 */
public class ConstanteActiva implements java.io.Serializable {

	private int identificador;
	private ConstanteVital constanteVital;
	private Residente residente;
	private int valorMaximo;
	private int valorMinimo;
	private Set emergenciaPorConstantes = new HashSet(0);
	private Set constanteLeidas = new HashSet(0);

	public ConstanteActiva() {
	}

	public ConstanteActiva(int identificador, ConstanteVital constanteVital,
			int valorMaximo, int valorMinimo) {
		this.identificador = identificador;
		this.constanteVital = constanteVital;
		this.valorMaximo = valorMaximo;
		this.valorMinimo = valorMinimo;
	}

	public ConstanteActiva(int identificador, ConstanteVital constanteVital,
			Residente residente, int valorMaximo, int valorMinimo,
			Set emergenciaPorConstantes, Set constanteLeidas) {
		this.identificador = identificador;
		this.constanteVital = constanteVital;
		this.residente = residente;
		this.valorMaximo = valorMaximo;
		this.valorMinimo = valorMinimo;
		this.emergenciaPorConstantes = emergenciaPorConstantes;
		this.constanteLeidas = constanteLeidas;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public ConstanteVital getConstanteVital() {
		return this.constanteVital;
	}

	public void setConstanteVital(ConstanteVital constanteVital) {
		this.constanteVital = constanteVital;
	}

	public Residente getResidente() {
		return this.residente;
	}

	public void setResidente(Residente residente) {
		this.residente = residente;
	}

	public int getValorMaximo() {
		return this.valorMaximo;
	}

	public void setValorMaximo(int valorMaximo) {
		this.valorMaximo = valorMaximo;
	}

	public int getValorMinimo() {
		return this.valorMinimo;
	}

	public void setValorMinimo(int valorMinimo) {
		this.valorMinimo = valorMinimo;
	}

	public Set getEmergenciaPorConstantes() {
		return this.emergenciaPorConstantes;
	}

	public void setEmergenciaPorConstantes(Set emergenciaPorConstantes) {
		this.emergenciaPorConstantes = emergenciaPorConstantes;
	}

	public Set getConstanteLeidas() {
		return this.constanteLeidas;
	}

	public void setConstanteLeidas(Set constanteLeidas) {
		this.constanteLeidas = constanteLeidas;
	}

}
