package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * EmergenciaDeResidentePorPermanenciaProlongada generated by hbm2java
 */
public class EmergenciaDeResidentePorPermanenciaProlongada implements
		java.io.Serializable {

	private int identificadorEmergergencia;
	private Estancia estancia;
	private NotificacionDeEmergencia notificacionDeEmergencia;

	public EmergenciaDeResidentePorPermanenciaProlongada() {
	}

	public EmergenciaDeResidentePorPermanenciaProlongada(Estancia estancia,
			NotificacionDeEmergencia notificacionDeEmergencia) {
		this.estancia = estancia;
		this.notificacionDeEmergencia = notificacionDeEmergencia;
	}

	public int getIdentificadorEmergergencia() {
		return this.identificadorEmergergencia;
	}

	public void setIdentificadorEmergergencia(int identificadorEmergergencia) {
		this.identificadorEmergergencia = identificadorEmergergencia;
	}

	public Estancia getEstancia() {
		return this.estancia;
	}

	public void setEstancia(Estancia estancia) {
		this.estancia = estancia;
	}

	public NotificacionDeEmergencia getNotificacionDeEmergencia() {
		return this.notificacionDeEmergencia;
	}

	public void setNotificacionDeEmergencia(
			NotificacionDeEmergencia notificacionDeEmergencia) {
		this.notificacionDeEmergencia = notificacionDeEmergencia;
	}

}
