package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EmergenciaPorConstante generated by hbm2java
 */
public class EmergenciaPorConstante implements java.io.Serializable {

	private int identificadorEmergencia;
	private NotificacionDeEmergencia notificacionDeEmergencia;
	private String nombre;
	private Set constanteActivas = new HashSet(0);

	public EmergenciaPorConstante() {
	}

	public EmergenciaPorConstante(
			NotificacionDeEmergencia notificacionDeEmergencia, String nombre) {
		this.notificacionDeEmergencia = notificacionDeEmergencia;
		this.nombre = nombre;
	}

	public EmergenciaPorConstante(
			NotificacionDeEmergencia notificacionDeEmergencia, String nombre,
			Set constanteActivas) {
		this.notificacionDeEmergencia = notificacionDeEmergencia;
		this.nombre = nombre;
		this.constanteActivas = constanteActivas;
	}

	public int getIdentificadorEmergencia() {
		return this.identificadorEmergencia;
	}

	public void setIdentificadorEmergencia(int identificadorEmergencia) {
		this.identificadorEmergencia = identificadorEmergencia;
	}

	public NotificacionDeEmergencia getNotificacionDeEmergencia() {
		return this.notificacionDeEmergencia;
	}

	public void setNotificacionDeEmergencia(
			NotificacionDeEmergencia notificacionDeEmergencia) {
		this.notificacionDeEmergencia = notificacionDeEmergencia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getConstanteActivas() {
		return this.constanteActivas;
	}

	public void setConstanteActivas(Set constanteActivas) {
		this.constanteActivas = constanteActivas;
	}

}
