package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Estancia generated by hbm2java
 */
public class Estancia implements java.io.Serializable {

	private int identificador;
	private Casa casa;
	private String nombre;
	private int identificadorRfid;
	private int tiempoDePermanenciaMaxima;
	private Set emergenciaDeResidentePorPermanenciaProlongadas = new HashSet(0);
	private Set residentes = new HashSet(0);

	public Estancia() {
	}

	public Estancia(int identificador, String nombre, int identificadorRfid,
			int tiempoDePermanenciaMaxima) {
		this.identificador = identificador;
		this.nombre = nombre;
		this.identificadorRfid = identificadorRfid;
		this.tiempoDePermanenciaMaxima = tiempoDePermanenciaMaxima;
	}

	public Estancia(int identificador, Casa casa, String nombre,
			int identificadorRfid, int tiempoDePermanenciaMaxima,
			Set emergenciaDeResidentePorPermanenciaProlongadas, Set residentes) {
		this.identificador = identificador;
		this.casa = casa;
		this.nombre = nombre;
		this.identificadorRfid = identificadorRfid;
		this.tiempoDePermanenciaMaxima = tiempoDePermanenciaMaxima;
		this.emergenciaDeResidentePorPermanenciaProlongadas = emergenciaDeResidentePorPermanenciaProlongadas;
		this.residentes = residentes;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public Casa getCasa() {
		return this.casa;
	}

	public void setCasa(Casa casa) {
		this.casa = casa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getIdentificadorRfid() {
		return this.identificadorRfid;
	}

	public void setIdentificadorRfid(int identificadorRfid) {
		this.identificadorRfid = identificadorRfid;
	}

	public int getTiempoDePermanenciaMaxima() {
		return this.tiempoDePermanenciaMaxima;
	}

	public void setTiempoDePermanenciaMaxima(int tiempoDePermanenciaMaxima) {
		this.tiempoDePermanenciaMaxima = tiempoDePermanenciaMaxima;
	}

	public Set getEmergenciaDeResidentePorPermanenciaProlongadas() {
		return this.emergenciaDeResidentePorPermanenciaProlongadas;
	}

	public void setEmergenciaDeResidentePorPermanenciaProlongadas(
			Set emergenciaDeResidentePorPermanenciaProlongadas) {
		this.emergenciaDeResidentePorPermanenciaProlongadas = emergenciaDeResidentePorPermanenciaProlongadas;
	}

	public Set getResidentes() {
		return this.residentes;
	}

	public void setResidentes(Set residentes) {
		this.residentes = residentes;
	}

}
