package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Guardia generated by hbm2java
 */
public class Guardia implements java.io.Serializable {

	private int identificador;
	private Cuidador cuidador;
	private Residente residente;
	private String fechaInicio;
	private String fechaFin;
	private String horaInicio;
	private String horaFin;
	private Set solicitudDeCambioDeGuardias = new HashSet(0);

	public Guardia() {
	}

	public Guardia(int identificador, Cuidador cuidador, Residente residente,
			String fechaInicio, String fechaFin, String horaInicio,
			String horaFin) {
		this.identificador = identificador;
		this.cuidador = cuidador;
		this.residente = residente;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
	}

	public Guardia(int identificador, Cuidador cuidador, Residente residente,
			String fechaInicio, String fechaFin, String horaInicio,
			String horaFin, Set solicitudDeCambioDeGuardias) {
		this.identificador = identificador;
		this.cuidador = cuidador;
		this.residente = residente;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.solicitudDeCambioDeGuardias = solicitudDeCambioDeGuardias;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public Cuidador getCuidador() {
		return this.cuidador;
	}

	public void setCuidador(Cuidador cuidador) {
		this.cuidador = cuidador;
	}

	public Residente getResidente() {
		return this.residente;
	}

	public void setResidente(Residente residente) {
		this.residente = residente;
	}

	public String getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(String fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(String horaInicio) {
		this.horaInicio = horaInicio;
	}

	public String getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(String horaFin) {
		this.horaFin = horaFin;
	}

	public Set getSolicitudDeCambioDeGuardias() {
		return this.solicitudDeCambioDeGuardias;
	}

	public void setSolicitudDeCambioDeGuardias(Set solicitudDeCambioDeGuardias) {
		this.solicitudDeCambioDeGuardias = solicitudDeCambioDeGuardias;
	}

}
