package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * NotificacionDeEmergencia generated by hbm2java
 */
public class NotificacionDeEmergencia implements java.io.Serializable {

	private int identificador;
	private Cuidador cuidador;
	private Residente residente;
	private String detalleTecnico;
	private boolean estaConfirmada;
	private String fecha;
	private String gravedad;
	private String momento;
	private String tipo;
	private String estado;
	private EmergenciaDeResidentePorPermanenciaProlongada emergenciaDeResidentePorPermanenciaProlongada;
	private EmergenciaPorConstante emergenciaPorConstante;

	public NotificacionDeEmergencia() {
	}

	public NotificacionDeEmergencia(int identificador, Cuidador cuidador,
			boolean estaConfirmada, String fecha, String gravedad, String tipo,
			String estado) {
		this.identificador = identificador;
		this.cuidador = cuidador;
		this.estaConfirmada = estaConfirmada;
		this.fecha = fecha;
		this.gravedad = gravedad;
		this.tipo = tipo;
		this.estado = estado;
	}

	public NotificacionDeEmergencia(
			int identificador,
			Cuidador cuidador,
			Residente residente,
			String detalleTecnico,
			boolean estaConfirmada,
			String fecha,
			String gravedad,
			String momento,
			String tipo,
			String estado,
			EmergenciaDeResidentePorPermanenciaProlongada emergenciaDeResidentePorPermanenciaProlongada,
			EmergenciaPorConstante emergenciaPorConstante) {
		this.identificador = identificador;
		this.cuidador = cuidador;
		this.residente = residente;
		this.detalleTecnico = detalleTecnico;
		this.estaConfirmada = estaConfirmada;
		this.fecha = fecha;
		this.gravedad = gravedad;
		this.momento = momento;
		this.tipo = tipo;
		this.estado = estado;
		this.emergenciaDeResidentePorPermanenciaProlongada = emergenciaDeResidentePorPermanenciaProlongada;
		this.emergenciaPorConstante = emergenciaPorConstante;
		this.cuidador = cuidador;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public Residente getResidente() {
		return this.residente;
	}

	public void setResidente(Residente residente) {
		this.residente = residente;
	}

	public String getDetalleTecnico() {
		return this.detalleTecnico;
	}

	public void setDetalleTecnico(String detalleTecnico) {
		this.detalleTecnico = detalleTecnico;
	}

	public boolean isEstaConfirmada() {
		return this.estaConfirmada;
	}

	public void setEstaConfirmada(boolean estaConfirmada) {
		this.estaConfirmada = estaConfirmada;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getGravedad() {
		return this.gravedad;
	}

	public void setGravedad(String gravedad) {
		this.gravedad = gravedad;
	}

	public String getMomento() {
		return this.momento;
	}

	public void setMomento(String momento) {
		this.momento = momento;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public EmergenciaDeResidentePorPermanenciaProlongada getEmergenciaDeResidentePorPermanenciaProlongada() {
		return this.emergenciaDeResidentePorPermanenciaProlongada;
	}

	public void setEmergenciaDeResidentePorPermanenciaProlongada(
			EmergenciaDeResidentePorPermanenciaProlongada emergenciaDeResidentePorPermanenciaProlongada) {
		this.emergenciaDeResidentePorPermanenciaProlongada = emergenciaDeResidentePorPermanenciaProlongada;
	}

	public EmergenciaPorConstante getEmergenciaPorConstante() {
		return this.emergenciaPorConstante;
	}

	public void setEmergenciaPorConstante(
			EmergenciaPorConstante emergenciaPorConstante) {
		this.emergenciaPorConstante = emergenciaPorConstante;
	}

	public Cuidador getCuidador() {
		return this.cuidador;
	}

	public void setCuidador(Cuidador cuidador) {
		this.cuidador = cuidador;
	}

}
