package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PatronDeRepeticion generated by hbm2java
 */
public class PatronDeRepeticion implements java.io.Serializable {

	private int identificador;
	private int cantidad;
	private int repeticiones;
	private String tipo;
	private Set recordatorios = new HashSet(0);

	public PatronDeRepeticion() {
	}

	public PatronDeRepeticion(int identificador, int cantidad,
			int repeticiones, String tipo) {
		this.identificador = identificador;
		this.cantidad = cantidad;
		this.repeticiones = repeticiones;
		this.tipo = tipo;
	}

	public PatronDeRepeticion(int identificador, int cantidad,
			int repeticiones, String tipo, Set recordatorios) {
		this.identificador = identificador;
		this.cantidad = cantidad;
		this.repeticiones = repeticiones;
		this.tipo = tipo;
		this.recordatorios = recordatorios;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public int getRepeticiones() {
		return this.repeticiones;
	}

	public void setRepeticiones(int repeticiones) {
		this.repeticiones = repeticiones;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getRecordatorios() {
		return this.recordatorios;
	}

	public void setRecordatorios(Set recordatorios) {
		this.recordatorios = recordatorios;
	}

}
