package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso implements java.io.Serializable {

	private int identificador;
	private String descripcion;
	private Set perfils = new HashSet(0);

	public Permiso() {
	}

	public Permiso(int identificador) {
		this.identificador = identificador;
	}

	public Permiso(int identificador, String descripcion, Set perfils) {
		this.identificador = identificador;
		this.descripcion = descripcion;
		this.perfils = perfils;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set perfils) {
		this.perfils = perfils;
	}

}
