package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * Recordatorio generated by hbm2java
 */
public class Recordatorio implements java.io.Serializable {

	private int identificador;
	private PatronDeRepeticion patronDeRepeticion;
	private Residente residente;
	private Calendario calendario;
	private String fechaInicio;
	private String fechaFin;
	private String lugar;
	private String motivo;

	public Recordatorio() {
	}

	public Recordatorio(int identificador,
			PatronDeRepeticion patronDeRepeticion, Residente residente,
			Calendario calendario, String fechaInicio, String fechaFin) {
		this.identificador = identificador;
		this.patronDeRepeticion = patronDeRepeticion;
		this.residente = residente;
		this.calendario = calendario;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Recordatorio(int identificador,
			PatronDeRepeticion patronDeRepeticion, Residente residente,
			Calendario calendario, String fechaInicio, String fechaFin,
			String lugar, String motivo) {
		this.identificador = identificador;
		this.patronDeRepeticion = patronDeRepeticion;
		this.residente = residente;
		this.calendario = calendario;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.lugar = lugar;
		this.motivo = motivo;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public PatronDeRepeticion getPatronDeRepeticion() {
		return this.patronDeRepeticion;
	}

	public void setPatronDeRepeticion(PatronDeRepeticion patronDeRepeticion) {
		this.patronDeRepeticion = patronDeRepeticion;
	}

	public Residente getResidente() {
		return this.residente;
	}

	public void setResidente(Residente residente) {
		this.residente = residente;
	}

	public Calendario getCalendario() {
		return this.calendario;
	}

	public void setCalendario(Calendario calendario) {
		this.calendario = calendario;
	}

	public String getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(String fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

}
