package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Residente generated by hbm2java
 */
public class Residente implements java.io.Serializable {

	private int identificador;
	private Estancia estancia;
	private Casa casa;
	private ServicioDeEmergencias servicioDeEmergencias;
	private ServicioResidente servicioResidente;
	private Set notificacionDeEmergencias = new HashSet(0);
	private Set cuidadors = new HashSet(0);
	private Set guardias = new HashSet(0);
	private Set recordatorios = new HashSet(0);
	private Set constanteActivas = new HashSet(0);

	public Residente() {
	}

	public Residente(ServicioDeEmergencias servicioDeEmergencias,
			ServicioResidente servicioResidente) {
		this.servicioDeEmergencias = servicioDeEmergencias;
		this.servicioResidente = servicioResidente;
	}

	public Residente(Estancia estancia, Casa casa,
			ServicioDeEmergencias servicioDeEmergencias,
			ServicioResidente servicioResidente, Set notificacionDeEmergencias,
			Set cuidadors, Set guardias, Set recordatorios, Set constanteActivas) {
		this.estancia = estancia;
		this.casa = casa;
		this.servicioDeEmergencias = servicioDeEmergencias;
		this.servicioResidente = servicioResidente;
		this.notificacionDeEmergencias = notificacionDeEmergencias;
		this.cuidadors = cuidadors;
		this.guardias = guardias;
		this.recordatorios = recordatorios;
		this.constanteActivas = constanteActivas;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public Estancia getEstancia() {
		return this.estancia;
	}

	public void setEstancia(Estancia estancia) {
		this.estancia = estancia;
	}

	public Casa getCasa() {
		return this.casa;
	}

	public void setCasa(Casa casa) {
		this.casa = casa;
	}

	public ServicioDeEmergencias getServicioDeEmergencias() {
		return this.servicioDeEmergencias;
	}

	public void setServicioDeEmergencias(
			ServicioDeEmergencias servicioDeEmergencias) {
		this.servicioDeEmergencias = servicioDeEmergencias;
	}

	public ServicioResidente getServicioResidente() {
		return this.servicioResidente;
	}

	public void setServicioResidente(ServicioResidente servicioResidente) {
		this.servicioResidente = servicioResidente;
	}

	public Set getNotificacionDeEmergencias() {
		return this.notificacionDeEmergencias;
	}

	public void setNotificacionDeEmergencias(Set notificacionDeEmergencias) {
		this.notificacionDeEmergencias = notificacionDeEmergencias;
	}

	public Set getCuidadors() {
		return this.cuidadors;
	}

	public void setCuidadors(Set cuidadors) {
		this.cuidadors = cuidadors;
	}

	public Set getGuardias() {
		return this.guardias;
	}

	public void setGuardias(Set guardias) {
		this.guardias = guardias;
	}

	public Set getRecordatorios() {
		return this.recordatorios;
	}

	public void setRecordatorios(Set recordatorios) {
		this.recordatorios = recordatorios;
	}

	public Set getConstanteActivas() {
		return this.constanteActivas;
	}

	public void setConstanteActivas(Set constanteActivas) {
		this.constanteActivas = constanteActivas;
	}

}
