package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * RestriccionHoraria generated by hbm2java
 */
public class RestriccionHoraria implements java.io.Serializable {

	private RestriccionHorariaId id;
	private Cuidador cuidador;

	public RestriccionHoraria() {
	}

	public RestriccionHoraria(RestriccionHorariaId id, Cuidador cuidador) {
		this.id = id;
		this.cuidador = cuidador;
	}

	public RestriccionHorariaId getId() {
		return this.id;
	}

	public void setId(RestriccionHorariaId id) {
		this.id = id;
	}

	public Cuidador getCuidador() {
		return this.cuidador;
	}

	public void setCuidador(Cuidador cuidador) {
		this.cuidador = cuidador;
	}

}
