package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * RestriccionHorariaId generated by hbm2java
 */
public class RestriccionHorariaId implements java.io.Serializable {

	private String horaInici;
	private String diaSemana;
	private int identficadorResidente;
	private String horaFin;

	public RestriccionHorariaId() {
	}

	public RestriccionHorariaId(String horaInici, String diaSemana,
			int identficadorResidente, String horaFin) {
		this.horaInici = horaInici;
		this.diaSemana = diaSemana;
		this.identficadorResidente = identficadorResidente;
		this.horaFin = horaFin;
	}

	public String getHoraInici() {
		return this.horaInici;
	}

	public void setHoraInici(String horaInici) {
		this.horaInici = horaInici;
	}

	public String getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(String diaSemana) {
		this.diaSemana = diaSemana;
	}

	public int getIdentficadorResidente() {
		return this.identficadorResidente;
	}

	public void setIdentficadorResidente(int identficadorResidente) {
		this.identficadorResidente = identficadorResidente;
	}

	public String getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(String horaFin) {
		this.horaFin = horaFin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RestriccionHorariaId))
			return false;
		RestriccionHorariaId castOther = (RestriccionHorariaId) other;

		return ((this.getHoraInici() == castOther.getHoraInici()) || (this
				.getHoraInici() != null && castOther.getHoraInici() != null && this
				.getHoraInici().equals(castOther.getHoraInici())))
				&& ((this.getDiaSemana() == castOther.getDiaSemana()) || (this
						.getDiaSemana() != null
						&& castOther.getDiaSemana() != null && this
						.getDiaSemana().equals(castOther.getDiaSemana())))
				&& (this.getIdentficadorResidente() == castOther
						.getIdentficadorResidente())
				&& ((this.getHoraFin() == castOther.getHoraFin()) || (this
						.getHoraFin() != null && castOther.getHoraFin() != null && this
						.getHoraFin().equals(castOther.getHoraFin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHoraInici() == null ? 0 : this.getHoraInici().hashCode());
		result = 37 * result
				+ (getDiaSemana() == null ? 0 : this.getDiaSemana().hashCode());
		result = 37 * result + this.getIdentficadorResidente();
		result = 37 * result
				+ (getHoraFin() == null ? 0 : this.getHoraFin().hashCode());
		return result;
	}

}
