package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * ServicioResidenteId generated by hbm2java
 */
public class ServicioResidenteId implements java.io.Serializable {

	private int identificadorResidente;
	private int identificadorServicio;

	public ServicioResidenteId() {
	}

	public ServicioResidenteId(int identificadorResidente,
			int identificadorServicio) {
		this.identificadorResidente = identificadorResidente;
		this.identificadorServicio = identificadorServicio;
	}

	public int getIdentificadorResidente() {
		return this.identificadorResidente;
	}

	public void setIdentificadorResidente(int identificadorResidente) {
		this.identificadorResidente = identificadorResidente;
	}

	public int getIdentificadorServicio() {
		return this.identificadorServicio;
	}

	public void setIdentificadorServicio(int identificadorServicio) {
		this.identificadorServicio = identificadorServicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServicioResidenteId))
			return false;
		ServicioResidenteId castOther = (ServicioResidenteId) other;

		return (this.getIdentificadorResidente() == castOther
				.getIdentificadorResidente())
				&& (this.getIdentificadorServicio() == castOther
						.getIdentificadorServicio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdentificadorResidente();
		result = 37 * result + this.getIdentificadorServicio();
		return result;
	}

}
