package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * ServicioPosicionamiento generated by hbm2java
 */
public class ServicioPosicionamiento implements java.io.Serializable {

	private int identificador;
	private Servicio servicio;
	private String horaEstanciaFin;
	private String horaEstanciaInicio;

	public ServicioPosicionamiento() {
	}

	public ServicioPosicionamiento(Servicio servicio) {
		this.servicio = servicio;
	}

	public ServicioPosicionamiento(Servicio servicio, String horaEstanciaFin,
			String horaEstanciaInicio) {
		this.servicio = servicio;
		this.horaEstanciaFin = horaEstanciaFin;
		this.horaEstanciaInicio = horaEstanciaInicio;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	public String getHoraEstanciaFin() {
		return this.horaEstanciaFin;
	}

	public void setHoraEstanciaFin(String horaEstanciaFin) {
		this.horaEstanciaFin = horaEstanciaFin;
	}

	public String getHoraEstanciaInicio() {
		return this.horaEstanciaInicio;
	}

	public void setHoraEstanciaInicio(String horaEstanciaInicio) {
		this.horaEstanciaInicio = horaEstanciaInicio;
	}

}
