package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ServicioDeEmergencias generated by hbm2java
 */
public class ServicioDeEmergencias implements java.io.Serializable {

	private int identificador;
	private String nombre;
	private String telefono;
	private String informacionAdicional;
	private Set residentes = new HashSet(0);

	public ServicioDeEmergencias() {
	}

	public ServicioDeEmergencias(int identificador, String nombre) {
		this.identificador = identificador;
		this.nombre = nombre;
	}

	public ServicioDeEmergencias(int identificador, String nombre,
			String telefono, String informacionAdicional, Set residentes) {
		this.identificador = identificador;
		this.nombre = nombre;
		this.telefono = telefono;
		this.informacionAdicional = informacionAdicional;
		this.residentes = residentes;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getInformacionAdicional() {
		return this.informacionAdicional;
	}

	public void setInformacionAdicional(String informacionAdicional) {
		this.informacionAdicional = informacionAdicional;
	}

	public Set getResidentes() {
		return this.residentes;
	}

	public void setResidentes(Set residentes) {
		this.residentes = residentes;
	}

}
