package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio implements java.io.Serializable {

	private int identificador;
	private String idHardware;
	private ServicioCaidas servicioCaidas;
	private Set servicioResidentes = new HashSet(0);
	private ServicioPosicionamiento servicioPosicionamiento;
	private ServicioBotonPanico servicioBotonPanico;
	private ServicioConstantes servicioConstantes;

	public Servicio() {
	}

	public Servicio(int identificador) {
		this.identificador = identificador;
	}

	public Servicio(int identificador, String idHardware,
			ServicioCaidas servicioCaidas, Set servicioResidentes,
			ServicioPosicionamiento servicioPosicionamiento,
			ServicioBotonPanico servicioBotonPanico,
			ServicioConstantes servicioConstantes) {
		this.identificador = identificador;
		this.idHardware = idHardware;
		this.servicioCaidas = servicioCaidas;
		this.servicioResidentes = servicioResidentes;
		this.servicioPosicionamiento = servicioPosicionamiento;
		this.servicioBotonPanico = servicioBotonPanico;
		this.servicioConstantes = servicioConstantes;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public String getIdHardware() {
		return this.idHardware;
	}

	public void setIdHardware(String idHardware) {
		this.idHardware = idHardware;
	}

	public ServicioCaidas getServicioCaidas() {
		return this.servicioCaidas;
	}

	public void setServicioCaidas(ServicioCaidas servicioCaidas) {
		this.servicioCaidas = servicioCaidas;
	}

	public Set getServicioResidentes() {
		return this.servicioResidentes;
	}

	public void setServicioResidentes(Set servicioResidentes) {
		this.servicioResidentes = servicioResidentes;
	}

	public ServicioPosicionamiento getServicioPosicionamiento() {
		return this.servicioPosicionamiento;
	}

	public void setServicioPosicionamiento(
			ServicioPosicionamiento servicioPosicionamiento) {
		this.servicioPosicionamiento = servicioPosicionamiento;
	}

	public ServicioBotonPanico getServicioBotonPanico() {
		return this.servicioBotonPanico;
	}

	public void setServicioBotonPanico(ServicioBotonPanico servicioBotonPanico) {
		this.servicioBotonPanico = servicioBotonPanico;
	}

	public ServicioConstantes getServicioConstantes() {
		return this.servicioConstantes;
	}

	public void setServicioConstantes(ServicioConstantes servicioConstantes) {
		this.servicioConstantes = servicioConstantes;
	}

}
