package modelo;

// Generated 04-ene-2013 11:21:16 by Hibernate Tools 3.4.0.CR1

/**
 * SolicitudDeCambioDeGuardia generated by hbm2java
 */
public class SolicitudDeCambioDeGuardia implements java.io.Serializable {

	private int identificador;
	private Cuidador cuidador;
	private Guardia guardia;
	private int identificadorSolicitante;
	private String fecha;
	private String motivo;
	private String email;

	public SolicitudDeCambioDeGuardia() {
	}

	public SolicitudDeCambioDeGuardia(int identificador, Cuidador cuidador,
			Guardia guardia, int identificadorSolicitante, String fecha,
			String email) {
		this.identificador = identificador;
		this.cuidador = cuidador;
		this.guardia = guardia;
		this.identificadorSolicitante = identificadorSolicitante;
		this.fecha = fecha;
		this.email = email;
	}

	public SolicitudDeCambioDeGuardia(int identificador, Cuidador cuidador,
			Guardia guardia, int identificadorSolicitante, String fecha,
			String motivo, String email) {
		this.identificador = identificador;
		this.cuidador = cuidador;
		this.guardia = guardia;
		this.identificadorSolicitante = identificadorSolicitante;
		this.fecha = fecha;
		this.motivo = motivo;
		this.email = email;
	}

	public int getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(int identificador) {
		this.identificador = identificador;
	}

	public Cuidador getCuidador() {
		return this.cuidador;
	}

	public void setCuidador(Cuidador cuidador) {
		this.cuidador = cuidador;
	}

	public Guardia getGuardia() {
		return this.guardia;
	}

	public void setGuardia(Guardia guardia) {
		this.guardia = guardia;
	}

	public int getIdentificadorSolicitante() {
		return this.identificadorSolicitante;
	}

	public void setIdentificadorSolicitante(int identificadorSolicitante) {
		this.identificadorSolicitante = identificadorSolicitante;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
